### ISSUE TITLE
Focus items in RESTful API 

### ISSUE THREAD

**Issue by xserve98** [i-love-flamingo/flamingo#138]
hello.
 Whether optimization of the REST API project will be considered later？

 I intend to use this for RESTful projects that do not require the functionality of templates

**Comment by bastianccm** [comment]
hi,

you can use Flamingo without a template engine already.
However there is no focus on REST APIs yet. We will however add a better routing and handling for APIs pretty soon.
In the meantime there is the Flamingo GraphQL module, based on gqlgen: https://github.com/i-love-flamingo/graphql

**Comment by xserve98** [comment]
Ok. Looking update。

**Comment by xserve98** [comment]
@bastianccm  Whether to consider Support [Casbin](https://github.com/casbin/casbin) as the authorization backend ?

Casbin is an authorization library that supports models like ACL, RBAC, ABAC.

Related to RBAC, Casbin has several advantages:

roles can be cascaded, aka roles can have roles.
support resource roles, so users have their roles and resource have their roles too. role = group here.
the permission assignments (or policy in Casbin's language) can be persisted in files or database (MySQL and Cassandra).
And you can even customize your own access control model, for example, mix RBAC and ABAC together by using roles and attributes at the same time. It's very flexible.

Casbin can provide more flexibility and security than the current ACL.

**Comment by bastianccm** [comment]
Hi, casbin was not yet considered, but I will now of course!
I'll ping you in the next days.

**Comment by xserve98** [comment]
Hi,
Is there any progress?

**Comment by bastianccm** [comment]
Hi @xserve98 sorry for the late response, crazy times currently.

Regarding API: we are currently investigating and designing what the best approach would be to be as compatible with existing projects as possible.
Do you have any example on what you would want to achieve? Then we can take that into account?

Regarding Casbin: I am currently unsure if casbin or OPA's Rego (https://www.openpolicyagent.org/docs/latest/#rego) would be the best option, so I'm looking into both of them right now to better understand their advantages and sweet-spots.

**Comment by xserve98** [comment]
Hi @bastianccm  Do you consider caching common modules instead of caching for httpclient?

Does the route support groups and middleware for groups? 

```
authorized := gin.Group("/admin", gin.BasicAuth(gin.Accounts{
		"foo":    "bar",
}))
authorized.GET("/secrets", func(c *gin.Context) {
})
```

**Comment by hsluoyz** [comment]
Hi, I'm Casbin author. I think Casbin would be a good choice for several points:

1. It is the most popular library for Golang authorization.
2. It is very friendly to serve as authz middleware for web frameworks. We want to hear all voices. https://casbin.org/docs/en/middlewares
3. Its community is growing fast. Actually, we have been accepted by Google Summer of Code 2020 recently: https://summerofcode.withgoogle.com/organizations/4699557545377792/
