### ISSUE TITLE
Configuring Flamingo for HTTPS

### ISSUE THREAD

**Issue by jacobscunn07** [i-love-flamingo/flamingo#153]
How can I configure Flamingo to serve over HTTPS? I've looked all over in the docs, but found no mentions of how to do this. Any help would be greatly appreciated.

**Comment by bastianccm** [comment]
Hi @jacobscunn07 

Actually this feature got lost, as usually Flamingo was used with a reverse-Proxy setup, e.g. in Kubernetes.

However I readded it, and apologize for forgetting it.
Please take a look at: https://github.com/i-love-flamingo/flamingo/tree/master/examples/hello-world

There is no release tag yet, so `go get -v flamingo.me/flamingo/v3@6d43b63` is necessary to get the most-recent version.

**Comment by jacobscunn07** [comment]
Awesome @bastianccm. When should this make it into a release tag, do you think?

That makes sense. My other (dotnet) apps are running on http in kubernetes with a reverse proxy, but just wanted to make sure flamingo could support https if we ever decided to terminate inside the cluster.

**Comment by bastianccm** [comment]
You're welcome! A new release should be due soon, once I had a few moments reviewing merge requests & co.
