### ISSUE TITLE
Config errors are not explained well

### ISSUE THREAD

**Issue by danielpoe** [i-love-flamingo/flamingo#155]
e.g.:

DEBUG=1 CONTEXT=dev:testproducts go run main.go serve
panic: error converting YAML to JSON: yaml: line 131: did not find expected key

goroutine 1 [running]:
flamingo.me/flamingo/v3/framework/config.loadYamlConfig(0xc00047f680, 0xc000276000, 0xc49, 0xc80, 0xe76, 0x0)
	/Users/daniel.poetzinger/Development/GOMOD/flamingo/flamingo/framework/config/loader.go:206 +0x1a2
flamingo.me/flamingo/v3/framework/config.loadYamlFile(0xc00047f680, 0xc000300fa0, 0xd, 0xd, 0x1)
	/Users/daniel.poetzinger/Development/GOMOD/flamingo/flamingo/framework/config/loader.go:181 +0x222

Maybe the lines around the error can be printed - its not clear which file etc its referreing to

**Comment by tessig** [comment]
fixed by #163
