### ISSUE TITLE
empty flamingo.StdLogger not usable

### ISSUE THREAD

**Issue by bastianccm** [i-love-flamingo/flamingo#161]
new(flamingo.StdLogger).Debug(...) will panic, as the underlying log.Logger is not ready to use anymore.

Tested with go 1.14.6

**Comment by tessig** [comment]
A solution can be to initialize the Logger field if not set.

**Comment by nico-i** [comment]
I would like to try to solve this issue. @bastianccm can you please assign it to me in regards to hacktoberfest?

**Comment by nico-i** [comment]
@bastianccm Issue has been fixed in the abovehand PR.
