### ISSUE TITLE
core/locale: bad performance for translations endpoint in debug mode

### ISSUE THREAD

**Issue by SchiffFlieger** [i-love-flamingo/flamingo#193]
We noticed that the [translations endpoint](https://github.com/i-love-flamingo/flamingo/blob/master/core/locale/module.go#L47-L48) in the core/locale module is really slow in flamingo debug mode. This is because in debug mode, we reload the translation files for each translation (see [TranslateLabel](https://github.com/i-love-flamingo/flamingo/blob/master/core/locale/infrastructure/translation_service.go#L48) and [loadFiles](https://github.com/i-love-flamingo/flamingo/blob/master/core/locale/infrastructure/translation_service.go#L127) methods). In the translations endpoint we list every translation, so we reload the translation files hundreds of times.  It would make sense to only reload when necessary (e. g. a translation file changed).

**Comment by carstendietrich** [comment]
Guess we need to rework the translation service in general, the mentioned logic also leads to a data race, see #188
