### ISSUE TITLE
Some broken links in the documentation

### ISSUE THREAD

**Issue by vdespa** [i-love-flamingo/flamingo#2]
1. https://www.flamingo.me/flamingo-core.html#Start - clicking on Documentation leads to "https://docs.flamingo.me/" which returns "404 Not Found".

2. Same with the tutorials link: "Start your application and check out our tutorials." - "404 Not Found".

3. The link on top with Github should probably lead to https://github.com/i-love-flamingo and not to github.com

**Comment by thebod** [comment]
Hey, thanks!

1 and 3 are fixed already, will fix 2 asap.

**Comment by thebod** [comment]
Fixed, thanks again!
