### ISSUE TITLE
Update layout docs

### ISSUE THREAD

**Issue by nico-i** [i-love-flamingo/flamingo#287]
As a flamingo newbie I find [the documentation](https://docs.flamingo.me/2.%20Flamingo%20Core/3.%20Core%20Modules/Gotemplate.html#layout-templates) on how to use layouts with templates to be very sparse and confusing.

Things that I am missing:

- What exactly is a layout? - Single sentence description of the feature
- Filetype of a layout

> If you want to define a site template, just call different sub templates inside like

- inside of what?
- One continuous example instead of multiple small ones
- Filenames for the examples to determine the location of the example
- The difference between a "snippet" and a layout
- Full file examples at the end of the tldr; examples
- An explanation on how objects can be passed into templates like in `{{template "blocks/product.html" $p}}` for example

**Comment by nico-i** [comment]
I also think that this is a `good-first-issue`.

**Comment by tessig** [comment]
handled by #291
