### ISSUE TITLE
Opencensus Module sets X-Correlation-Id even if already present

### ISSUE THREAD

**Issue by nico-i** [i-love-flamingo/flamingo#304]
### Description
Currently the open census module adds a correlation id header and value to every HTTP request. This leads to problems in our project as we already use the X-Correlation-Id header in other contexts throughout our services.

### Proposed solution
To deal with this issue I suggest to modify the corresponding [module.go](https://github.com/i-love-flamingo/flamingo/blob/master/framework/opencensus/module.go#L50) to only set the X-Correlation-Id header if it isn't already present and to instead use the existing X-Correlation-Id value if it is.

### Acknowledgements
I know that the open census module has since been deprecated but as we are currently dealing with this problem and the ETA for open census' replacement is yet to be determined, I think taking on this issue is still viable.

**Comment by tessig** [comment]
closed by #310
