### ISSUE TITLE
Links which are currently not working or are broken

### ISSUE THREAD

**Issue by ResuBaka** [i-love-flamingo/flamingo#40]
These two links are not working.
https://docs.flamingo.me/2.%20Flamingo%20Core/1.%20Flamingo%20Basics/2.%20Flamingo%20Project%20Structure.html
![image](https://user-images.githubusercontent.com/15260832/58751895-9b362d00-84a5-11e9-979b-2662434ba3ca.png)

https://docs.flamingo.me/1.%20Introduction/1.%20Getting%20Started.html
![image](https://user-images.githubusercontent.com/15260832/58751907-ce78bc00-84a5-11e9-8895-388e5642cd0c.png)

**Comment by tessig** [comment]
was fixed by @jadhub and will be deployed very soon :)
