### ISSUE TITLE
GOMAXPROCS configurable

### ISSUE THREAD

**Issue by danielpoe** [i-love-flamingo/flamingo#77]
Finding from "PET Team":

Der runtime-scheduler hat eine Funktion “GOMAXPROCS”, welche der runtime grob mitteilt wieviele parallele Verarbeitungen sie machen kann. Dieser Wert ist per default die Anzahl der Verfügbaren cores (seit 1.5). In einer Container Umgebung ist das trotz limits die Gesamtanzahl der Cores der darunterlegenden Node.
Da so der go-runtime-scheduler glaubt 4 cpu’s zur Verfügung zu haben, die aber per cgroup auf etwa 2 limitiert sind (aktuell bei kso), versucht go mehr zu parallelisieren als eigentlich möglich ist. Auch das führt zu unnötigem cfs-throtteling. Daher sollten wir das entsprechend des limits pro Projekt konfigurieren.

Ab Kubernetes Version 1.16 könnten wir dem Container exakte Kerne zuweisen (und damit die anderen verstecken). Da wir aber erst bei k8s 1.11 sind und es auch bei 1.16 noch Probleme damit gibt, können wir damit aktuell nicht arbeiten und nicht zeitnah rechnen. 

Entweder konfigurieren wir das per Umgebungsvariable pro Projekt und Stage manuell oder automatisiert mit dieser Library von Uber: https://github.com/uber-go/automaxprocs Diese setzt den Wert automatisch zur Startzeit der Applikation. Evt könnte man dies in den Flamingo-Core integrieren? Was meint ihr?

**Comment by thebod** [comment]
Well, `GOMAXPROCS` is an environment variable. You can set it whereever you want, e.g. in your kubernetes pod template. So it is already configurable (and has always been).

**Comment by thebod** [comment]
(keeping this open for now for discussion, @danielpoe @jochen42 anything else to discuss? now we have the autoconfiguration via #79, and as always the GOMAXPROCS variable.)

**Comment by jochen42** [comment]
thx @thebod ! i don't see anything else to discuss here.
